# development mode
## docker compose build
# production mode
## docker compose build --build-arg MODE=production
services:
  vite-app:
    build:
      context: ./vite-app
      args:
        - MODE=development
    image: vite-app:latest
    container_name: vite-app
    ports:
      - "80:80"
  nest-app:
    build: ./nest-app
    image: nest-app:latest
    container_name: nest-app
    ports:
      - "3000:3000"
  vite-nest-test:
    image: mcr.microsoft.com/playwright:v1.44.1-jammy
    container_name: vite-nest-test
    init: true
    ipc: host
    ports:
      - "9323:9323"
    volumes:
      # DevContainer 内で参照された場合はワークスペースフォルダをマウントする.
      # DevContainer 外で参照された場合はカレントディレクトリをマウントする.
      # see https://docs.docker.com/compose/environment-variables/env-file/#interpolation
      - ${LOCAL_WORKSPACE_FOLDER:-.}/vite-nest-test:/test
    depends_on:
      - vite-app
      - nest-app
    working_dir: /test
    command: npx playwright test
